<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  
  <name>HCL AppScan</name>
  <organization>
  	<name>HCL</name>
  	<url>https://www.hcl.com/</url>
  </organization>
  
  <url>https://github.com/jenkinsci/appscan-plugin</url>
	
  <licenses>
  	<license>
  		<name>Apache License, Version 2.0</name>
  		<url> https://www.apache.org/licenses/LICENSE-2.0</url>
  	</license>
  </licenses>
  
  <developers>
  	<developer>
      		<id>mattmurp</id>
      		<name>Matt Murphy</name>
      		<email>matthew.murphy@hcl.com</email>
    	</developer>
  </developers>
	
  <parent>
    <groupId>org.jenkins-ci.plugins</groupId>
    <artifactId>plugin</artifactId>
    <version>5.9</version>
    <relativePath />
  </parent>

  <properties>
    <slf4jVersion>1.7.26</slf4jVersion>
    <jenkins.baseline>2.479</jenkins.baseline>
    <jenkins.version>${jenkins.baseline}.3</jenkins.version>
    <findbugs.failOnError>false</findbugs.failOnError>
    <spotbugs.failOnError>false</spotbugs.failOnError>
  </properties>
	
  <groupId>com.hcl.security</groupId>
  <artifactId>appscan</artifactId>
  <version>1.8.5-SNAPSHOT</version>
  <description>This plugin allows you to execute security scans with HCL AppScan</description>
  <packaging>hpi</packaging>

  <dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.jenkins.tools.bom</groupId>
            <artifactId>bom-${jenkins.baseline}.x</artifactId>
            <version>4023.va_eeb_b_4e45f07</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
  </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.hcl</groupId>
            <artifactId>appscan.sdk</artifactId>
            <version>1.1.12</version>
        </dependency>
        <dependency>
            <groupId>org.apache.wink</groupId>
            <artifactId>wink-json4j</artifactId>
            <version>1.4</version>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>credentials</artifactId>
        </dependency>
    </dependencies>

  <repositories>
    <repository>
        <id>repo.jenkins-ci.org</id>
        <url>https://repo.jenkins-ci.org/public/</url>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>repo.jenkins-ci.org</id>
      <url>https://repo.jenkins-ci.org/public/</url>
    </pluginRepository>
  </pluginRepositories>

  <build>
    <!-- SCVS-4.18: Centralize and lock down all plugin versions -->
    <pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
            </plugin>
            <plugin>
                <groupId>org.jenkins-ci.tools</groupId>
                <artifactId>maven-hpi-plugin</artifactId>
                <version>3.57</version>
            </plugin>
            <!-- SCAL-PKGDEP-2: Enforcer plugin for locked plugin versions -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>3.5.0</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-artifact-plugin</artifactId>
                <version>3.5.1</version>
            </plugin>
        </plugins>
    </pluginManagement>

      <plugins>
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-compiler-plugin</artifactId>
              <configuration>
                  <release>17</release>
              </configuration>
          </plugin>

          <plugin>
              <groupId>org.jenkins-ci.tools</groupId>
              <artifactId>maven-hpi-plugin</artifactId>
          </plugin>

          <!-- SCAL-PKGDEP-2: Enforce fixed plugin versions & ban dynamic version ranges -->
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-enforcer-plugin</artifactId>
              <executions>
                  <execution>
                      <id>enforce-security-rules</id>
                      <goals>
                          <goal>enforce</goal>
                      </goals>
                      <configuration>
                          <rules>
                              <requirePluginVersions>
                                  <message>All Maven plugins must have explicit, fixed versions defined!</message>
                              </requirePluginVersions>
                              <banDynamicVersions>
                                  <message>Dynamic versions (ranges, LATEST, RELEASE) are strictly prohibited!</message>
                                  <allowSnapshots>false</allowSnapshots>
                              </banDynamicVersions>
                          </rules>
                      </configuration>
                  </execution>
              </executions>
          </plugin>
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-artifact-plugin</artifactId>
              <version>3.5.1</version>
              <executions>
                  <execution>
                      <id>build-checksums</id>
                      <goals>
                          <goal>buildinfo</goal>
                      </goals>
                  </execution>
              </executions>
          </plugin>
      </plugins>
  </build>
  
  <scm>
  	<connection>scm:git:https://github.com/jenkinsci/appscan-plugin.git</connection>
  	<developerConnection>scm:git:ssh://git@github.com/jenkinsci/appscan-plugin.git</developerConnection>
  	<url>https://github.com/jenkinsci/appscan-plugin</url>
    <tag>HEAD</tag>
  </scm>

</project>
